config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,controllers: { omniauth_callbacks: 'accounts/omniauth_callbacks' } 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  post "unfollow/account" => "accounts#unfollow_account", as: :unfollow_account
  post "post/delete" => "accounts#delete_post", as: :delete_post
  get "followers/:username" => "accounts#show_followers", as: :show_followers
  get "following/:username" => "accounts#show_following", as: :show_following
  resources :posts, only: [:new,:show,:create]
  resources :comments, only: [:create]
  root to: "public#homepage"
end

app/models/post.rb
class Post < ApplicationRecord
    default_scope{order created_at: :desc}
    #Ex:- :default =>''
    mount_uploader :image, ImageUploader
    belongs_to :account
    has_many :likes
    has_many :comments
    before_create :set_active
    scope :active, -> {where active: true}
    
    private
    def set_active
        self.active = true
    end
    
    def set_page
        self.per_page = 10
    end
end

app/controllers/posts_controller.rb
class PostsController <  ApplicationController
    before_action :authenticate_account!
    before_action :set_post, only: [:show]
    def  new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.account_id = current_account.id if account_signed_in?
        if @post.save
            redirect_to dashboard_path, flash: {success:"Post was created successfully"}
        else
            redirect_to new_post_path, flash: {danger:"Post was not saved"}
        end
    end

    
    
    def show
        @comment = Comment.new
        @comments = Comment.includes(:account).where(post_id: @post.id)
    end
    
    private
    def set_post
        @post = Post.find(params[:id]) if params[:id].present?
    end
    def post_params
        params.require(:post).permit(:image, :description, :image_cache)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
    def post_liked_by_user?(post_id)
        Like.where(post_id: post_id, account_id: current_account.id).any?
    end
end

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
    <div class="comment">
        <%=link_to profile_picture_thumb(comment.account), profile_path(comment.account.username)%>
        <strong><%= link_to comment.account.username,profile_path(comment.account.username) %></strong>
        <%= comment.comment %>
        <p class = "text-muted m-l-40" style="font-size: 13px">
        <%= time_ago_in_words comment.created_at%> ago </p>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
    <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control"%>
    <%= f.hidden_field :image_cache %>
    </div>
    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control"%>
    </div>
    <%= f.submit "Save Post", class: "btn btn-success"%>
<% end %>

app/views/posts/_post.html.erb
            <div class="insta-post">
                <div class="post-meta">
                    
                    <%=link_to profile_picture(post.account,30), profile_path(post.account.username)  %>
                    <%= link_to post.account.username, profile_path(post.account.username), class: "text-dark"%> 
                </div>
                <div class="post-image">
                    <%= image_tag post.image.url, class: "img img-fluid", style: "width: 100%;"%>
                </div>

                <div class="post-details">
                <div class="post-actions">
                    <i class= "fa fa-heart fa-2x like-<%= post.id %> <%= 'active' if post_liked_by_user?(post.id) %> post-like" data-id = "<%=post.id%>"> </i>
                    <%= link_to post_path(post.id) do %>
                    <i class= "fa fa-comment  fa-2x post-comment"></i>
                    <%end%>
                </div>
                    <p><strong id='post-<%= post.id%>-likes'><%= post.total_likes_count%> likes</strong></p>
                    <p><strong id='post-<%= post.id%>-comments'><%= link_to post.account.username, profile_path(post.account.username), class: "text-dark"%></strong></p>
                    <div class="desc"><%= simple_format post.description%></div>
                    <% if  !post.total_comments_count.nil? && post.total_comments_count>2 %>
                        <%= link_to post_path(post.id) do %>
                        <div class="text-muted" style="font-size: 14px">View all comments</div>
                        <%end%>
                    <%end%>
                    <p class="text-muted"><%= time_ago_in_words post.created_at%> ago</p>
                    <div class="comment-section"><%= render "posts/comments", post: post, comments: Comment.includes(:account).where(post_id: post.id)%></div>
                </div>
                <div class="comment-box ">
                    <%= form_for @comment do |f|%>
                        <%= f.hidden_field :post_id, value: post.id %>
                        <div class="input-group">
                            <%= f.text_field :comment, placeholder: "Add comment here...." ,class: "form-control post-comment"%>
                            <div class="input-group-append">
                                <%= f.submit :post, class: "btn btn-success float-right" %>
                            </div>
                        </div>
                    <% end %>
                </div>
                </div>
            

app/views/posts/like.js.erb
<% if @success == true%>
    $(".like-<%= @post_id %>").addClass("active");
<% else %>
    $(".like-<%= @post_id %>").removeClass("active");

<% end %>
    $("#post-<%= @post_id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="container post-details put-shadow">
    <div class="row">
        <div class="col-8">
            <div class="insta-post">
                 <%= image_tag @post.image.url, class: "img img-fluid" if @post.image.present? %>
            </div>
        </div>
        <div class="col-4">
                <div class="post-meta">
                    <%=link_to profile_picture(@post.account,30), profile_path(@post.account.username)  %>
                    <%= link_to @post.account.username, profile_path(@post.account.username), class: "text-dark"%>
                    <% if current_account.id == @post.account_id %>
                        <%= form_tag delete_post_path, method: :post, class: "float-right" do %>
                            <%= hidden_field_tag :post_id, @post.id %>
                            <%= hidden_field_tag :post_account_id, @post.account_id %>
                            <%= submit_tag "Delete", class: "btn btn-danger btn-sm "%>
                        <% end %>
                    <%end%> 
                </div>
                <div class="post-details">
                    <div class="comments-feed">
                    <%= simple_format @post.description%>
                        <%= render "posts/comments", post: @post, comments: @comments%>
                    </div>
                    <div class="post-actions">
                        <i class= "fa fa-heart fa-2x like-<%= @post.id %> <%= 'active' if post_liked_by_user?(@post.id) %> post-like" data-id = "<%=@post.id%>"> </i>
                        
                        <i class= "fa fa-comment  fa-2x post-comment", id="post-comment"></i>
                        
                    </div>
                    <p><strong id='post-<%= @post.id%>-likes'><%= @post.total_likes_count%> likes</strong></p>
                    

                    <p class="text-muted"><%= time_ago_in_words @post.created_at%> ago</p>
                </div>
                    <div class="comment-box">
                        <%= form_for @comment do |f|%>
                            <%= f.hidden_field :post_id, value: @post.id %>
                            <%= f.hidden_field :return_to, value: "post" %>
                            <div class="input-group">
                                <%= f.text_field :comment, placeholder: "Add comment here...." ,class: "form-control post-comment"%>
                                <div class="input-group-append">
                                    <%= f.submit :post, class: "btn btn-success float-right" %>
                                </div>
                            </div>
                        <% end %>
                    </div>
        </div>
        
    </div>
</div>