config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,controllers: { omniauth_callbacks: 'accounts/omniauth_callbacks' } 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  post "unfollow/account" => "accounts#unfollow_account", as: :unfollow_account
  post "post/delete" => "accounts#delete_post", as: :delete_post
  get "followers/:username" => "accounts#show_followers", as: :show_followers
  get "following/:username" => "accounts#show_following", as: :show_following
  resources :posts, only: [:new,:show,:create]
  resources :comments, only: [:create]
  root to: "public#homepage"
end

app/views/layouts/_account_nav.html.erb
<li class="nav-item active">
    <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
</li>

<li class="nav-item">
     <%= link_to "New Post", new_post_path, class: "nav-link" %>
</li>
<li class="nav-item">
     <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link" %>
</li>
<li class="nav-item">
    <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Sociogram</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body class="d-flex flex-column min-vh-100">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white static-top">
      <div class="container">
        <a class= "navbar-brand", href=<%= account_signed_in? ? dashboard_path : root_path %> >
        <i class="fa fa-instagram"> </i> &nbsp | Sociogram
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if account_signed_in? %>
              <%=render "layouts/account_nav"%>
            <% else %>
              <%= render "layouts/public_nav" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        <%= yield %>
          
        </div>
      </div>
    </div>
    </div>
    <footer class="py-3 mt-auto bg-white" style="border-top: 2px solid #dddd">
      <div class='text-center footer-copyright'>
      <a href="https://www.linkedin.com/in/prateek-thakare">Prateek Thakare</a>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>InstaDupe</title>
	<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<style>
  .cursive{
	  font-family: "Comic Sans MS", cursive, sans-serif;
  }
  </style>
</head>

  <body class="d-flex flex-column min-vh-100" >
    <%= image_tag 'background.jpg', class: "img img-fluid", id: 'bg'%>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        <h1 class="mt-5 cursive" style="color: white; padding-bottom: 10px;">Welcome to <i class="fa fa-instagram"> </i> Sociogram</h1>
        <%= yield %>
	
          
        </div>
      </div>
    </div>
    </div>
   
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Sociogram</title>
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
  .cursive{
	  font-family: "Comic Sans MS", cursive, sans-serif;
  }
  </style>
</head>

  <body class="d-flex flex-column min-vh-100">
    <%= image_tag 'background.jpg', class: "img img-fluid", id: 'bg'%>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        
<h1 class="mt-5 cursive" style="color: white;">Welcome to <i class="fa fa-instagram"> </i> Sociogram</h1><br>

<%= link_to "Sign up", new_account_registration_path, class:"btn btn-raised ", style: "color: white !important;" %>    
<%= link_to "Sign in", new_account_session_path, class:"btn btn-raised", style: "color: white !important; " %>
<%= link_to "Sign in with Facebook", account_facebook_omniauth_authorize_path, class: "btn btn-raised", style: "color: white !important;"%>
	
          
        </div>
      </div>
    </div>
    </div>
   
  </body>
</html>