config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,controllers: { omniauth_callbacks: 'accounts/omniauth_callbacks' } 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account
  post "unfollow/account" => "accounts#unfollow_account", as: :unfollow_account
  post "post/delete" => "accounts#delete_post", as: :delete_post
  get "followers/:username" => "accounts#show_followers", as: :show_followers
  get "following/:username" => "accounts#show_following", as: :show_following
  resources :posts, only: [:new,:show,:create]
  resources :comments, only: [:create]
  root to: "public#homepage"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  mount_uploader :image, ImageUploader
  has_many :posts 
  has_many :likes
  has_many :follwers
  has_many :following
  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(following_id: self.id).count
  end

  def total_following
    Follower.where(follower_id: self.id).count
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image 
      user.username = auth.info.name.gsub(" ","")# assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/accounts/omniauth_callbacks_controller.rb
class Accounts::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        # You need to implement the method below in your model (e.g. app/models/account.rb)
        @account = Account.from_omniauth(request.env["omniauth.auth"])
    
        if @account.persisted?
          sign_in_and_redirect @account, event: :authentication #this will throw if @account is not activated
          set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
        else
          session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
          redirect_to new_account_registration_url
        end
      end
    
      def failure
        redirect_to root_path
      end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_account, only: [:profile]

    def index
        #show posts
        followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
        # followers_ids << current_account.id
        @posts = Post.paginate(:page => params[:page], :per_page => 2).where(account_id: followers_ids).active
        respond_to do |format|
            format.html
            format.js
        end
        @comment = Comment.new
        following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
        following_ids << current_account.id
        @follower_suggestions = Account.where.not(id: following_ids)

    end

    def profile
        @posts = @account.posts.active
    end

    def show_followers
        @my_followers = Follower.where(following_id: current_account.id)
      end
    def show_following
        @my_following = Follower.where(follower_id: current_account.id)
      end

    def follow_account
        follower_id  = params[:follow_id]
        if Follower.create!(follower_id: current_account.id, following_id: follower_id )
            flash[:success]  = "Now Following user"
        else
            flash[:success] = "Unable to add Follower"
        end
        
        redirect_back(fallback_location: root_path)
    end

    def unfollow_account
        following_id = params[:follow_id]
        Follower.where(follower_id: current_account.id, following_id: following_id).destroy_all
        flash[:success] = "User unfollowed"
        redirect_back(fallback_location: root_path)
    end

    def delete_post
        post_account_id = params[:post_account_id].to_i
        post_id = params[:post_id].to_i
       
        if post_account_id == current_account.id
        
            if !Like.where(post_id: post_id).empty?
                Like.where(post_id: post_id).destroy_all 
            end
            if !Comment.where(post_id: post_id).empty? 
                Comment.where(post_id: post_id).destroy_all
            end
            Post.where(id: post_id).destroy_all
        end
        redirect_to profile_path(current_account.username)
    end
    
    private
    def set_account
        @account = Account.find_by_username(params[:username])
        
    end





end

app/helpers/accounts_helper.rb
module AccountsHelper

    def profile_picture account, width = 100
        image_path = account.image.present? ? account.image.url : "default.png" 
        image_tag(image_path,width: width, class: "img-circle m-r-10")
    end

    def profile_picture_thumb account, width = 30
        image_path = account.image.present? ? account.image.thumb.url : "default.png" 
        image_tag(image_path,width: width, class: "img-circle m-r-10")
    end

    def can_edit_profile? profile_id
        account_signed_in? && current_account.id == profile_id
    end
end

app/views/accounts/_follower_suggestions.html.erb
<div class="suggestions">
    <% @follower_suggestions.each do |account| %>
        <div class="recommended-follower">
            <div class=row>
                <div class="col-sm-3 col-lg-2">
                    <%=link_to profile_picture(account,35), profile_path(account.username)  %>
                </div>
                <div class="col-sm-9 col-lg-10">
                    <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
                    <%= hidden_field_tag :follow_id, account.id %>
                    <%= submit_tag "Follow", class: "btn btn-info btn-sm" %>
                    <% end %>

                    <%= link_to account.username, profile_path(account.username), class: "text-dark"%> 
                    
                    <% if account.created_at > 2.days.ago%> 
                    <p class="text-muted">
                        New to Instagram
                    </p>
                    <%else%>
                    <p class="text-muted">
                        Folowed by <%= account.total_followers%> users
                    </p>
                    <%end%>
                </div>

            </div>
        </div>
    <% end %>
    </div>

app/views/accounts/index.html.erb
<div class="Container">
    <div class="row">
        <div class="col-8" id="my-posts">
            <%= render @posts%>
            <div id="infinite-scrolling" style="display: none">
                <%= will_paginate @posts %>
            </div>
        </div>
        <div class="col-4">
        <div class="account-summary">
            <p class="m-0"><%=link_to image_tag(current_account.image.thumb.url, class: "m-r-15 img-circle float-left"), profile_path(current_account.username) if current_account.image.present? %> 
            <strong><%=link_to current_account.username, profile_path(current_account.username) %></strong><br>
             <span style="font-size: 15px"><%= current_account.full_name%></span>
            
            </p>
        </div>
        <div class="follower-suggestions">
       
        <strong><p class="text-muted">Suggestions for you</p></strong>
        <%= render "accounts/follower_suggestions" %>
        </div>
    </div>
</div>

app/views/accounts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/accounts/profile.html.erb
<div class="container">
    <div class="row">
        <div class="col-4",style="align-content: center">
        <%= profile_picture @account, 200 %>
        </div>
            <div class="col-8 text-left">
                <div class="row">
                    <div class="col-6">
                        <% if can_edit_profile?(@account.id) %>
                            <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-muted btn-custom float-right btn-sm", style: "margin-top: 10px" %>
                        <%elsif Follower.where(following_id: @account.id,follower_id: current_account.id).empty?%> 
                            <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
                                <%= hidden_field_tag :follow_id, @account.id %>
                                <%= submit_tag "Follow", class: "btn btn-info btn-sm", style: "margin-top: 10px"%>
                            <% end %>
                        <%else%>
                            <%=  form_tag unfollow_account_path, method: :post, class: "float-right" do %>
                                <%= hidden_field_tag :follow_id, @account.id %>
                                <%= submit_tag "Unfollow", class: "btn btn-info btn-danger btn-sm ", style: "margin-top: 10px"%>
                            <% end %>
                        <%end%>
                        <h1><%= @account.full_name%></h1>
                    </div>
                </div>
                <div class="row profile-stats">
                    <div class= "col-4">
                        <%= @account.posts.count%> Posts
                    </div>
                    <div class= "col-4">
                        <%= @account.total_followers%> 
                        <% if @account.total_followers>0%>
                            <%= link_to show_followers_path(@account.id) do %>
                                Followers
                            <% end %>
                        <% else %>
                            Followers
                        <% end %>
                    </div>
                    <div class= "col-4">
                        <%= @account.total_following %> 
                        <% if @account.total_following>0%>
                            <%= link_to show_following_path(@account.id) do %>
                                Following
                            <% end %>
                        <% else %>
                            Following
                        <% end %>
                    </div>
                </div>
                <p><%= @account.full_name%> </p>
                <%= simple_format @account.description%>
                <p><%= link_to @account.website if @account.website.present?%> </p>

            </div>
    </div>

            <div class="row profile">
            
                <% @posts.each do |post| %>
                    <div class="col-4">
                        <div class="insta-post post-square put-shadow", style="background: url(<%= post.image.url%>) no-repeat center top">
                            <%= link_to post_path(post) do  %>
                                <div class="post-stats">
                                    <div class="inner">
                                        <i class="fa fa-heart"></i> <%= post.total_likes_count%> 
                                        <i class="fa fa-comment m-l-15"></i> <%= post.total_comments_count%>
                                    </div>
                                </div>
                            <%end%>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>

app/views/accounts/show_followers.html.erb
<div class="container" style="max-width: 700px !important; text-align: center; padding: 20px"><h4>Your Followers</h4></div>
<div class="container main-container scroller">
    <% @my_followers.each do |follower|%>
                <% @account = Account.find_by_id(follower.follower_id)%>
                <% if !@account.nil? && !@account.username.nil?%>
                    <div class="container post-details follower-list put-shadow">
                        <div class="row" > 
                            <div class="col-sm-3 col-lg-2">
                                <%=link_to profile_picture(@account,40), profile_path(@account.username)  %>
                            </div>
                            <div class="col-sm-9 col-lg-10">
                                    <% if Follower.where(following_id: follower.follower_id,follower_id: follower.following_id).empty?%>
                                        <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
                                            <%= hidden_field_tag :follow_id, @account.id %>
                                            <%= submit_tag "Follow", class: "btn btn-info btn-sm"%>
                                        <% end %>
                                    <%else%>
                                        <%=  form_tag unfollow_account_path, method: :post, class: "float-right" do %>
                                            <%= hidden_field_tag :follow_id, @account.id %>
                                            <%= submit_tag "Unfollow", class: "btn btn-info btn-danger btn-sm "%>
                                        <% end %>
                                    <% end %>
                                <%= link_to @account.username, profile_path(@account.username), class: "text-dark"%> 
                                <p class="text-muted"><%= @account.full_name%></p>   
                            </div>
                        </div>
                    </div>
                <% end %>
            
    <%end%>
</div>

app/views/accounts/show_following.html.erb
<div class="container" style="max-width: 700px !important; text-align: center; padding: 20px"><h4>Your Following</h4></div>
<div class="container main-container scroller">
    <% @my_following.each do |following|%>
                <% @account = Account.find_by_id(following.following_id)%>
                <% if !@account.nil? && !@account.username.nil?%>
                    <div class="container post-details follower-list put-shadow">
                        <div class="row" > 
                            <div class="col-sm-3 col-lg-2">
                                <%=link_to profile_picture(@account,40), profile_path(@account.username)  %>
                            </div>
                            <div class="col-sm-9 col-lg-10">
                                <%= form_tag unfollow_account_path, method: :post, class: "float-right" do %>
                                <%= hidden_field_tag :follow_id, @account.id %>
                                <%= submit_tag "Unfollow", class: "btn btn-danger btn-sm" %>
                                <% end %>

                                <%= link_to @account.username, profile_path(@account.username), class: "text-dark"%> 
                                <p class="text-muted"><%= @account.full_name%></p>
                                
                                
                            </div>
                        </div>
                    </div>
                <% end %>
            
    <%end%>
</div>